create table PURCHASE_DETAILS(SL_NO varchar(30) UNIQUE,PRODUCT_ID varchar(30) PRIMARY KEY,PRODUCT_NAME varchar(30) UNIQUE,DATE datetime,MANUFACTURING_DATE dateTime,EXPIRIY_DATE datetime,QUANTITY varchar(30),DISTRIBUTE_NAME varchar(30),DISTRIBUTER_ADDRESS varchar(30),COST_PRICE varchar(30),CONTACT_NUMBER varchar(30))
SELECT * FROM PURCHASE_DETAILS
DROP table PURCHASE_DETAILS